# Generated by Django 4.0.2 on 2022-02-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
