# Generated by Django 4.0.2 on 2022-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeedetail_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='joiningdate',
            field=models.DateField(null=True),
        ),
    ]
