# Generated by Django 4.0.2 on 2022-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeedetail_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
